/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.6.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QLabel *background;
    QLabel *bird_1;
    QLabel *ground;
    QLabel *shoot_front;
    QLabel *shoot_back;
    QLabel *box_1;
    QLabel *box_3;
    QLabel *box_2;
    QLabel *box_4;
    QLabel *box_5;
    QLabel *box_6;
    QLabel *box_7;
    QLabel *rock_1;
    QLabel *rock_2;
    QLabel *rock_3;
    QLabel *rock_4;
    QLabel *rock_5;
    QLabel *rock_6;
    QLabel *rock_7;
    QLabel *rock_8;
    QLabel *rock_9;
    QLabel *rock_10;
    QLabel *label;
    QLabel *label_2;
    QLabel *label_3;
    QLabel *rock_11;
    QLabel *rock_12;
    QLabel *rock_13;
    QLabel *rock_14;
    QLabel *rock_15;
    QLabel *rock_16;
    QLabel *rock_17;
    QLabel *rock_18;
    QLabel *rock_19;
    QLabel *rock_20;
    QLabel *rock_21;
    QLabel *rock_22;
    QLabel *rock_23;
    QLabel *rock_24;
    QLabel *rock_25;
    QLabel *rock_26;
    QLabel *rock_27;
    QLabel *rock_28;
    QLabel *rock_29;
    QLabel *rock_30;
    QLabel *rock_31;
    QLabel *rock_32;
    QLabel *rock_33;
    QLabel *rock_34;
    QLabel *rock_35;
    QLabel *rock_36;
    QLabel *rock_37;
    QLabel *rock_38;
    QLabel *rock_39;
    QLabel *rock_40;
    QLabel *rock_41;
    QLabel *rock_42;
    QLabel *rock_43;
    QLabel *rock_44;
    QLabel *rock_45;
    QLabel *rock_46;
    QLabel *rock_47;
    QLabel *rock_48;
    QLabel *rock_49;
    QLabel *rock_50;
    QLabel *rock_51;
    QLabel *rock_52;
    QLabel *rock_53;
    QLabel *rock_54;
    QLabel *rock_55;
    QLabel *rock_56;
    QLabel *rock_57;
    QLabel *rock_58;
    QLabel *rock_59;
    QLabel *rock_60;
    QLabel *rock_61;
    QLabel *rock_62;
    QLabel *rock_63;
    QLabel *rock_64;
    QLabel *rock_65;
    QLabel *rock_66;
    QLabel *rock_67;
    QLabel *rock_68;
    QLabel *box_8;
    QLabel *box_9;
    QLabel *rock_69;
    QLabel *rock_70;
    QLabel *rock_71;
    QLabel *rock_72;
    QLabel *rock_73;
    QLabel *rock_74;
    QLabel *rock_75;
    QLabel *rock_76;
    QLabel *rock_77;
    QLabel *rock_78;
    QLabel *rock_79;
    QLabel *rock_80;
    QLabel *bottom_1;
    QLabel *bottom_2;
    QLabel *bottom_3;
    QLabel *egg;
    QLabel *break_1;
    QLabel *break_2;
    QLabel *break_3;
    QLabel *num_1;
    QLabel *num_2;
    QLabel *num_3;
    QLabel *num_4;
    QLabel *num_5;
    QLabel *label_4;
    QPushButton *quit;
    QLabel *pause;
    QLabel *label_5;
    QPushButton *again;
    QMenuBar *menuBar;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(1024, 768);
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        background = new QLabel(centralWidget);
        background->setObjectName(QStringLiteral("background"));
        background->setGeometry(QRect(0, 0, 1024, 768));
        background->setPixmap(QPixmap(QString::fromUtf8(":/pics/angry_bird_background_pics_2_ch.png")));
        bird_1 = new QLabel(centralWidget);
        bird_1->setObjectName(QStringLiteral("bird_1"));
        bird_1->setGeometry(QRect(150, 500, 50, 50));
        ground = new QLabel(centralWidget);
        ground->setObjectName(QStringLiteral("ground"));
        ground->setGeometry(QRect(0, 600, 1024, 168));
        ground->setPixmap(QPixmap(QString::fromUtf8(":/pics/ground_ch.png")));
        shoot_front = new QLabel(centralWidget);
        shoot_front->setObjectName(QStringLiteral("shoot_front"));
        shoot_front->setGeometry(QRect(40, 460, 275, 183));
        shoot_front->setPixmap(QPixmap(QString::fromUtf8(":/pics/shoot_ch_front.png")));
        shoot_back = new QLabel(centralWidget);
        shoot_back->setObjectName(QStringLiteral("shoot_back"));
        shoot_back->setGeometry(QRect(40, 462, 275, 183));
        shoot_back->setPixmap(QPixmap(QString::fromUtf8(":/pics/shoot_ch_back.png")));
        box_1 = new QLabel(centralWidget);
        box_1->setObjectName(QStringLiteral("box_1"));
        box_1->setGeometry(QRect(580, 550, 50, 50));
        box_1->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_4.png")));
        box_3 = new QLabel(centralWidget);
        box_3->setObjectName(QStringLiteral("box_3"));
        box_3->setGeometry(QRect(580, 450, 50, 50));
        box_3->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_4.png")));
        box_2 = new QLabel(centralWidget);
        box_2->setObjectName(QStringLiteral("box_2"));
        box_2->setGeometry(QRect(580, 500, 50, 50));
        box_2->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_4.png")));
        box_4 = new QLabel(centralWidget);
        box_4->setObjectName(QStringLiteral("box_4"));
        box_4->setGeometry(QRect(700, 550, 50, 50));
        box_4->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_4.png")));
        box_5 = new QLabel(centralWidget);
        box_5->setObjectName(QStringLiteral("box_5"));
        box_5->setGeometry(QRect(700, 500, 50, 50));
        box_5->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_4.png")));
        box_6 = new QLabel(centralWidget);
        box_6->setObjectName(QStringLiteral("box_6"));
        box_6->setGeometry(QRect(700, 450, 50, 50));
        box_6->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_4.png")));
        box_7 = new QLabel(centralWidget);
        box_7->setObjectName(QStringLiteral("box_7"));
        box_7->setGeometry(QRect(820, 550, 50, 50));
        box_7->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_4.png")));
        rock_1 = new QLabel(centralWidget);
        rock_1->setObjectName(QStringLiteral("rock_1"));
        rock_1->setGeometry(QRect(525, 340, 40, 20));
        rock_1->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_2 = new QLabel(centralWidget);
        rock_2->setObjectName(QStringLiteral("rock_2"));
        rock_2->setGeometry(QRect(565, 340, 40, 20));
        rock_2->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_3 = new QLabel(centralWidget);
        rock_3->setObjectName(QStringLiteral("rock_3"));
        rock_3->setGeometry(QRect(605, 340, 40, 20));
        rock_3->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_4 = new QLabel(centralWidget);
        rock_4->setObjectName(QStringLiteral("rock_4"));
        rock_4->setGeometry(QRect(645, 340, 40, 20));
        rock_4->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_5 = new QLabel(centralWidget);
        rock_5->setObjectName(QStringLiteral("rock_5"));
        rock_5->setGeometry(QRect(685, 340, 40, 20));
        rock_5->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_6 = new QLabel(centralWidget);
        rock_6->setObjectName(QStringLiteral("rock_6"));
        rock_6->setGeometry(QRect(725, 340, 40, 20));
        rock_6->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_7 = new QLabel(centralWidget);
        rock_7->setObjectName(QStringLiteral("rock_7"));
        rock_7->setGeometry(QRect(765, 340, 40, 20));
        rock_7->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_8 = new QLabel(centralWidget);
        rock_8->setObjectName(QStringLiteral("rock_8"));
        rock_8->setGeometry(QRect(805, 340, 40, 20));
        rock_8->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_9 = new QLabel(centralWidget);
        rock_9->setObjectName(QStringLiteral("rock_9"));
        rock_9->setGeometry(QRect(845, 340, 40, 20));
        rock_9->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_10 = new QLabel(centralWidget);
        rock_10->setObjectName(QStringLiteral("rock_10"));
        rock_10->setGeometry(QRect(885, 340, 40, 20));
        rock_10->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        label = new QLabel(centralWidget);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(580, 410, 50, 50));
        label->setPixmap(QPixmap(QString::fromUtf8(":/pics/pig.png")));
        label_2 = new QLabel(centralWidget);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(700, 410, 50, 50));
        label_2->setPixmap(QPixmap(QString::fromUtf8(":/pics/pig.png")));
        label_3 = new QLabel(centralWidget);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(820, 410, 50, 50));
        label_3->setPixmap(QPixmap(QString::fromUtf8(":/pics/pig.png")));
        rock_11 = new QLabel(centralWidget);
        rock_11->setObjectName(QStringLiteral("rock_11"));
        rock_11->setGeometry(QRect(525, 280, 40, 20));
        rock_11->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_12 = new QLabel(centralWidget);
        rock_12->setObjectName(QStringLiteral("rock_12"));
        rock_12->setGeometry(QRect(525, 500, 40, 20));
        rock_12->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_13 = new QLabel(centralWidget);
        rock_13->setObjectName(QStringLiteral("rock_13"));
        rock_13->setGeometry(QRect(525, 520, 40, 20));
        rock_13->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_14 = new QLabel(centralWidget);
        rock_14->setObjectName(QStringLiteral("rock_14"));
        rock_14->setGeometry(QRect(525, 540, 40, 20));
        rock_14->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_15 = new QLabel(centralWidget);
        rock_15->setObjectName(QStringLiteral("rock_15"));
        rock_15->setGeometry(QRect(525, 560, 40, 20));
        rock_15->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_16 = new QLabel(centralWidget);
        rock_16->setObjectName(QStringLiteral("rock_16"));
        rock_16->setGeometry(QRect(525, 580, 40, 20));
        rock_16->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_17 = new QLabel(centralWidget);
        rock_17->setObjectName(QStringLiteral("rock_17"));
        rock_17->setGeometry(QRect(765, 260, 40, 20));
        rock_17->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_18 = new QLabel(centralWidget);
        rock_18->setObjectName(QStringLiteral("rock_18"));
        rock_18->setGeometry(QRect(765, 280, 40, 20));
        rock_18->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_19 = new QLabel(centralWidget);
        rock_19->setObjectName(QStringLiteral("rock_19"));
        rock_19->setGeometry(QRect(765, 300, 40, 20));
        rock_19->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_20 = new QLabel(centralWidget);
        rock_20->setObjectName(QStringLiteral("rock_20"));
        rock_20->setGeometry(QRect(885, 260, 40, 20));
        rock_20->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_21 = new QLabel(centralWidget);
        rock_21->setObjectName(QStringLiteral("rock_21"));
        rock_21->setGeometry(QRect(885, 280, 40, 20));
        rock_21->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_22 = new QLabel(centralWidget);
        rock_22->setObjectName(QStringLiteral("rock_22"));
        rock_22->setGeometry(QRect(885, 300, 40, 20));
        rock_22->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_23 = new QLabel(centralWidget);
        rock_23->setObjectName(QStringLiteral("rock_23"));
        rock_23->setGeometry(QRect(885, 320, 40, 20));
        rock_23->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_24 = new QLabel(centralWidget);
        rock_24->setObjectName(QStringLiteral("rock_24"));
        rock_24->setGeometry(QRect(845, 320, 40, 20));
        rock_24->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_25 = new QLabel(centralWidget);
        rock_25->setObjectName(QStringLiteral("rock_25"));
        rock_25->setGeometry(QRect(805, 320, 40, 20));
        rock_25->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_26 = new QLabel(centralWidget);
        rock_26->setObjectName(QStringLiteral("rock_26"));
        rock_26->setGeometry(QRect(765, 320, 40, 20));
        rock_26->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_27 = new QLabel(centralWidget);
        rock_27->setObjectName(QStringLiteral("rock_27"));
        rock_27->setGeometry(QRect(725, 320, 40, 20));
        rock_27->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_28 = new QLabel(centralWidget);
        rock_28->setObjectName(QStringLiteral("rock_28"));
        rock_28->setGeometry(QRect(685, 320, 40, 20));
        rock_28->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_29 = new QLabel(centralWidget);
        rock_29->setObjectName(QStringLiteral("rock_29"));
        rock_29->setGeometry(QRect(645, 320, 40, 20));
        rock_29->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_30 = new QLabel(centralWidget);
        rock_30->setObjectName(QStringLiteral("rock_30"));
        rock_30->setGeometry(QRect(605, 320, 40, 20));
        rock_30->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_31 = new QLabel(centralWidget);
        rock_31->setObjectName(QStringLiteral("rock_31"));
        rock_31->setGeometry(QRect(565, 320, 40, 20));
        rock_31->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_32 = new QLabel(centralWidget);
        rock_32->setObjectName(QStringLiteral("rock_32"));
        rock_32->setGeometry(QRect(525, 320, 40, 20));
        rock_32->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_33 = new QLabel(centralWidget);
        rock_33->setObjectName(QStringLiteral("rock_33"));
        rock_33->setGeometry(QRect(525, 300, 40, 20));
        rock_33->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_34 = new QLabel(centralWidget);
        rock_34->setObjectName(QStringLiteral("rock_34"));
        rock_34->setGeometry(QRect(525, 480, 40, 20));
        rock_34->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_35 = new QLabel(centralWidget);
        rock_35->setObjectName(QStringLiteral("rock_35"));
        rock_35->setGeometry(QRect(525, 460, 40, 20));
        rock_35->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_36 = new QLabel(centralWidget);
        rock_36->setObjectName(QStringLiteral("rock_36"));
        rock_36->setGeometry(QRect(525, 440, 40, 20));
        rock_36->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_37 = new QLabel(centralWidget);
        rock_37->setObjectName(QStringLiteral("rock_37"));
        rock_37->setGeometry(QRect(525, 420, 40, 20));
        rock_37->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_38 = new QLabel(centralWidget);
        rock_38->setObjectName(QStringLiteral("rock_38"));
        rock_38->setGeometry(QRect(525, 400, 40, 20));
        rock_38->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_39 = new QLabel(centralWidget);
        rock_39->setObjectName(QStringLiteral("rock_39"));
        rock_39->setGeometry(QRect(525, 380, 40, 20));
        rock_39->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_40 = new QLabel(centralWidget);
        rock_40->setObjectName(QStringLiteral("rock_40"));
        rock_40->setGeometry(QRect(525, 360, 40, 20));
        rock_40->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_41 = new QLabel(centralWidget);
        rock_41->setObjectName(QStringLiteral("rock_41"));
        rock_41->setGeometry(QRect(525, 260, 40, 20));
        rock_41->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_42 = new QLabel(centralWidget);
        rock_42->setObjectName(QStringLiteral("rock_42"));
        rock_42->setGeometry(QRect(645, 300, 40, 20));
        rock_42->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_43 = new QLabel(centralWidget);
        rock_43->setObjectName(QStringLiteral("rock_43"));
        rock_43->setGeometry(QRect(645, 280, 40, 20));
        rock_43->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_44 = new QLabel(centralWidget);
        rock_44->setObjectName(QStringLiteral("rock_44"));
        rock_44->setGeometry(QRect(645, 260, 40, 20));
        rock_44->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_45 = new QLabel(centralWidget);
        rock_45->setObjectName(QStringLiteral("rock_45"));
        rock_45->setGeometry(QRect(645, 360, 40, 20));
        rock_45->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_46 = new QLabel(centralWidget);
        rock_46->setObjectName(QStringLiteral("rock_46"));
        rock_46->setGeometry(QRect(645, 380, 40, 20));
        rock_46->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_47 = new QLabel(centralWidget);
        rock_47->setObjectName(QStringLiteral("rock_47"));
        rock_47->setGeometry(QRect(645, 400, 40, 20));
        rock_47->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_48 = new QLabel(centralWidget);
        rock_48->setObjectName(QStringLiteral("rock_48"));
        rock_48->setGeometry(QRect(645, 420, 40, 20));
        rock_48->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_49 = new QLabel(centralWidget);
        rock_49->setObjectName(QStringLiteral("rock_49"));
        rock_49->setGeometry(QRect(645, 440, 40, 20));
        rock_49->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_50 = new QLabel(centralWidget);
        rock_50->setObjectName(QStringLiteral("rock_50"));
        rock_50->setGeometry(QRect(645, 460, 40, 20));
        rock_50->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_51 = new QLabel(centralWidget);
        rock_51->setObjectName(QStringLiteral("rock_51"));
        rock_51->setGeometry(QRect(645, 480, 40, 20));
        rock_51->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_52 = new QLabel(centralWidget);
        rock_52->setObjectName(QStringLiteral("rock_52"));
        rock_52->setGeometry(QRect(645, 500, 40, 20));
        rock_52->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_53 = new QLabel(centralWidget);
        rock_53->setObjectName(QStringLiteral("rock_53"));
        rock_53->setGeometry(QRect(645, 520, 40, 20));
        rock_53->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_54 = new QLabel(centralWidget);
        rock_54->setObjectName(QStringLiteral("rock_54"));
        rock_54->setGeometry(QRect(645, 540, 40, 20));
        rock_54->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_55 = new QLabel(centralWidget);
        rock_55->setObjectName(QStringLiteral("rock_55"));
        rock_55->setGeometry(QRect(645, 560, 40, 20));
        rock_55->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_56 = new QLabel(centralWidget);
        rock_56->setObjectName(QStringLiteral("rock_56"));
        rock_56->setGeometry(QRect(645, 580, 40, 20));
        rock_56->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_57 = new QLabel(centralWidget);
        rock_57->setObjectName(QStringLiteral("rock_57"));
        rock_57->setGeometry(QRect(765, 360, 40, 20));
        rock_57->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_58 = new QLabel(centralWidget);
        rock_58->setObjectName(QStringLiteral("rock_58"));
        rock_58->setGeometry(QRect(765, 380, 40, 20));
        rock_58->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_59 = new QLabel(centralWidget);
        rock_59->setObjectName(QStringLiteral("rock_59"));
        rock_59->setGeometry(QRect(765, 400, 40, 20));
        rock_59->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_60 = new QLabel(centralWidget);
        rock_60->setObjectName(QStringLiteral("rock_60"));
        rock_60->setGeometry(QRect(765, 420, 40, 20));
        rock_60->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_61 = new QLabel(centralWidget);
        rock_61->setObjectName(QStringLiteral("rock_61"));
        rock_61->setGeometry(QRect(765, 440, 40, 20));
        rock_61->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_62 = new QLabel(centralWidget);
        rock_62->setObjectName(QStringLiteral("rock_62"));
        rock_62->setGeometry(QRect(765, 460, 40, 20));
        rock_62->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_63 = new QLabel(centralWidget);
        rock_63->setObjectName(QStringLiteral("rock_63"));
        rock_63->setGeometry(QRect(765, 540, 40, 20));
        rock_63->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_64 = new QLabel(centralWidget);
        rock_64->setObjectName(QStringLiteral("rock_64"));
        rock_64->setGeometry(QRect(765, 480, 40, 20));
        rock_64->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_65 = new QLabel(centralWidget);
        rock_65->setObjectName(QStringLiteral("rock_65"));
        rock_65->setGeometry(QRect(765, 520, 40, 20));
        rock_65->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_66 = new QLabel(centralWidget);
        rock_66->setObjectName(QStringLiteral("rock_66"));
        rock_66->setGeometry(QRect(765, 500, 40, 20));
        rock_66->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_67 = new QLabel(centralWidget);
        rock_67->setObjectName(QStringLiteral("rock_67"));
        rock_67->setGeometry(QRect(765, 560, 40, 20));
        rock_67->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_68 = new QLabel(centralWidget);
        rock_68->setObjectName(QStringLiteral("rock_68"));
        rock_68->setGeometry(QRect(765, 580, 40, 20));
        rock_68->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        box_8 = new QLabel(centralWidget);
        box_8->setObjectName(QStringLiteral("box_8"));
        box_8->setGeometry(QRect(820, 500, 50, 50));
        box_8->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_4.png")));
        box_9 = new QLabel(centralWidget);
        box_9->setObjectName(QStringLiteral("box_9"));
        box_9->setGeometry(QRect(820, 450, 50, 50));
        box_9->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_4.png")));
        rock_69 = new QLabel(centralWidget);
        rock_69->setObjectName(QStringLiteral("rock_69"));
        rock_69->setGeometry(QRect(885, 360, 40, 20));
        rock_69->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_70 = new QLabel(centralWidget);
        rock_70->setObjectName(QStringLiteral("rock_70"));
        rock_70->setGeometry(QRect(885, 380, 40, 20));
        rock_70->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_71 = new QLabel(centralWidget);
        rock_71->setObjectName(QStringLiteral("rock_71"));
        rock_71->setGeometry(QRect(885, 400, 40, 20));
        rock_71->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_72 = new QLabel(centralWidget);
        rock_72->setObjectName(QStringLiteral("rock_72"));
        rock_72->setGeometry(QRect(885, 420, 40, 20));
        rock_72->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_73 = new QLabel(centralWidget);
        rock_73->setObjectName(QStringLiteral("rock_73"));
        rock_73->setGeometry(QRect(885, 440, 40, 20));
        rock_73->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_74 = new QLabel(centralWidget);
        rock_74->setObjectName(QStringLiteral("rock_74"));
        rock_74->setGeometry(QRect(885, 460, 40, 20));
        rock_74->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_75 = new QLabel(centralWidget);
        rock_75->setObjectName(QStringLiteral("rock_75"));
        rock_75->setGeometry(QRect(885, 480, 40, 20));
        rock_75->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_76 = new QLabel(centralWidget);
        rock_76->setObjectName(QStringLiteral("rock_76"));
        rock_76->setGeometry(QRect(885, 500, 40, 20));
        rock_76->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_77 = new QLabel(centralWidget);
        rock_77->setObjectName(QStringLiteral("rock_77"));
        rock_77->setGeometry(QRect(885, 520, 40, 20));
        rock_77->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_78 = new QLabel(centralWidget);
        rock_78->setObjectName(QStringLiteral("rock_78"));
        rock_78->setGeometry(QRect(885, 540, 40, 20));
        rock_78->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_79 = new QLabel(centralWidget);
        rock_79->setObjectName(QStringLiteral("rock_79"));
        rock_79->setGeometry(QRect(885, 560, 40, 20));
        rock_79->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        rock_80 = new QLabel(centralWidget);
        rock_80->setObjectName(QStringLiteral("rock_80"));
        rock_80->setGeometry(QRect(885, 580, 40, 20));
        rock_80->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9.png")));
        bottom_1 = new QLabel(centralWidget);
        bottom_1->setObjectName(QStringLiteral("bottom_1"));
        bottom_1->setGeometry(QRect(585, 300, 40, 20));
        bottom_1->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9_ch.png")));
        bottom_2 = new QLabel(centralWidget);
        bottom_2->setObjectName(QStringLiteral("bottom_2"));
        bottom_2->setGeometry(QRect(705, 300, 40, 20));
        bottom_2->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9_ch.png")));
        bottom_3 = new QLabel(centralWidget);
        bottom_3->setObjectName(QStringLiteral("bottom_3"));
        bottom_3->setGeometry(QRect(825, 300, 40, 20));
        bottom_3->setPixmap(QPixmap(QString::fromUtf8(":/pics/things_9_ch.png")));
        egg = new QLabel(centralWidget);
        egg->setObjectName(QStringLiteral("egg"));
        egg->setGeometry(QRect(310, 180, 47, 12));
        break_1 = new QLabel(centralWidget);
        break_1->setObjectName(QStringLiteral("break_1"));
        break_1->setGeometry(QRect(575, 360, 60, 20));
        break_2 = new QLabel(centralWidget);
        break_2->setObjectName(QStringLiteral("break_2"));
        break_2->setGeometry(QRect(695, 360, 60, 20));
        break_3 = new QLabel(centralWidget);
        break_3->setObjectName(QStringLiteral("break_3"));
        break_3->setGeometry(QRect(815, 360, 60, 20));
        num_1 = new QLabel(centralWidget);
        num_1->setObjectName(QStringLiteral("num_1"));
        num_1->setGeometry(QRect(180, 20, 51, 60));
        num_2 = new QLabel(centralWidget);
        num_2->setObjectName(QStringLiteral("num_2"));
        num_2->setGeometry(QRect(210, 20, 50, 60));
        num_3 = new QLabel(centralWidget);
        num_3->setObjectName(QStringLiteral("num_3"));
        num_3->setGeometry(QRect(240, 20, 50, 60));
        num_4 = new QLabel(centralWidget);
        num_4->setObjectName(QStringLiteral("num_4"));
        num_4->setGeometry(QRect(270, 20, 50, 60));
        num_5 = new QLabel(centralWidget);
        num_5->setObjectName(QStringLiteral("num_5"));
        num_5->setGeometry(QRect(300, 20, 50, 60));
        label_4 = new QLabel(centralWidget);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(40, 25, 141, 51));
        quit = new QPushButton(centralWidget);
        quit->setObjectName(QStringLiteral("quit"));
        quit->setGeometry(QRect(20, 90, 141, 151));
        quit->setStyleSheet(QLatin1String("background-image: url(:/pics/pause2.png);\n"
"background-color: rgb(0, 0, 0);"));
        pause = new QLabel(centralWidget);
        pause->setObjectName(QStringLiteral("pause"));
        pause->setGeometry(QRect(0, 90, 201, 721));
        pause->setPixmap(QPixmap(QString::fromUtf8(":/pics/pause.png")));
        label_5 = new QLabel(centralWidget);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(23, 90, 141, 151));
        label_5->setPixmap(QPixmap(QString::fromUtf8(":/pics/pause2.png")));
        again = new QPushButton(centralWidget);
        again->setObjectName(QStringLiteral("again"));
        again->setGeometry(QRect(20, 250, 141, 151));
        again->setStyleSheet(QLatin1String("background-image: url(:/pics/pause2.png);\n"
"background-color: rgb(0, 0, 0);"));
        MainWindow->setCentralWidget(centralWidget);
        background->raise();
        bottom_2->raise();
        bottom_1->raise();
        ground->raise();
        shoot_back->raise();
        bird_1->raise();
        box_1->raise();
        box_3->raise();
        box_2->raise();
        box_4->raise();
        box_5->raise();
        box_6->raise();
        box_7->raise();
        rock_1->raise();
        rock_2->raise();
        rock_3->raise();
        rock_4->raise();
        rock_5->raise();
        rock_6->raise();
        rock_7->raise();
        rock_8->raise();
        rock_9->raise();
        rock_10->raise();
        label->raise();
        label_2->raise();
        label_3->raise();
        rock_11->raise();
        rock_12->raise();
        rock_13->raise();
        rock_14->raise();
        rock_15->raise();
        rock_16->raise();
        rock_17->raise();
        rock_18->raise();
        rock_19->raise();
        rock_20->raise();
        rock_21->raise();
        rock_22->raise();
        rock_23->raise();
        rock_24->raise();
        rock_25->raise();
        rock_26->raise();
        rock_27->raise();
        rock_28->raise();
        rock_29->raise();
        rock_30->raise();
        rock_31->raise();
        rock_32->raise();
        rock_33->raise();
        rock_34->raise();
        rock_35->raise();
        rock_36->raise();
        rock_37->raise();
        rock_38->raise();
        rock_39->raise();
        rock_40->raise();
        rock_41->raise();
        rock_42->raise();
        rock_43->raise();
        rock_44->raise();
        rock_45->raise();
        rock_46->raise();
        rock_47->raise();
        rock_48->raise();
        rock_49->raise();
        rock_50->raise();
        rock_51->raise();
        rock_52->raise();
        rock_53->raise();
        rock_54->raise();
        rock_55->raise();
        rock_56->raise();
        rock_57->raise();
        rock_58->raise();
        rock_59->raise();
        rock_60->raise();
        rock_61->raise();
        rock_62->raise();
        rock_63->raise();
        rock_64->raise();
        rock_65->raise();
        rock_66->raise();
        rock_67->raise();
        rock_68->raise();
        box_8->raise();
        box_9->raise();
        rock_69->raise();
        rock_70->raise();
        rock_71->raise();
        rock_72->raise();
        rock_73->raise();
        rock_74->raise();
        rock_75->raise();
        rock_76->raise();
        rock_77->raise();
        rock_78->raise();
        rock_79->raise();
        rock_80->raise();
        bottom_3->raise();
        shoot_front->raise();
        egg->raise();
        break_1->raise();
        break_2->raise();
        break_3->raise();
        num_1->raise();
        num_2->raise();
        num_3->raise();
        num_4->raise();
        num_5->raise();
        label_4->raise();
        pause->raise();
        label_5->raise();
        quit->raise();
        again->raise();
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 1024, 21));
        MainWindow->setMenuBar(menuBar);
        mainToolBar = new QToolBar(MainWindow);
        mainToolBar->setObjectName(QStringLiteral("mainToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        MainWindow->setStatusBar(statusBar);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", 0));
        background->setText(QString());
        bird_1->setText(QString());
        ground->setText(QString());
        shoot_front->setText(QString());
        shoot_back->setText(QString());
        box_1->setText(QString());
        box_3->setText(QString());
        box_2->setText(QString());
        box_4->setText(QString());
        box_5->setText(QString());
        box_6->setText(QString());
        box_7->setText(QString());
        rock_1->setText(QString());
        rock_2->setText(QString());
        rock_3->setText(QString());
        rock_4->setText(QString());
        rock_5->setText(QString());
        rock_6->setText(QString());
        rock_7->setText(QString());
        rock_8->setText(QString());
        rock_9->setText(QString());
        rock_10->setText(QString());
        label->setText(QString());
        label_2->setText(QString());
        label_3->setText(QString());
        rock_11->setText(QString());
        rock_12->setText(QString());
        rock_13->setText(QString());
        rock_14->setText(QString());
        rock_15->setText(QString());
        rock_16->setText(QString());
        rock_17->setText(QString());
        rock_18->setText(QString());
        rock_19->setText(QString());
        rock_20->setText(QString());
        rock_21->setText(QString());
        rock_22->setText(QString());
        rock_23->setText(QString());
        rock_24->setText(QString());
        rock_25->setText(QString());
        rock_26->setText(QString());
        rock_27->setText(QString());
        rock_28->setText(QString());
        rock_29->setText(QString());
        rock_30->setText(QString());
        rock_31->setText(QString());
        rock_32->setText(QString());
        rock_33->setText(QString());
        rock_34->setText(QString());
        rock_35->setText(QString());
        rock_36->setText(QString());
        rock_37->setText(QString());
        rock_38->setText(QString());
        rock_39->setText(QString());
        rock_40->setText(QString());
        rock_41->setText(QString());
        rock_42->setText(QString());
        rock_43->setText(QString());
        rock_44->setText(QString());
        rock_45->setText(QString());
        rock_46->setText(QString());
        rock_47->setText(QString());
        rock_48->setText(QString());
        rock_49->setText(QString());
        rock_50->setText(QString());
        rock_51->setText(QString());
        rock_52->setText(QString());
        rock_53->setText(QString());
        rock_54->setText(QString());
        rock_55->setText(QString());
        rock_56->setText(QString());
        rock_57->setText(QString());
        rock_58->setText(QString());
        rock_59->setText(QString());
        rock_60->setText(QString());
        rock_61->setText(QString());
        rock_62->setText(QString());
        rock_63->setText(QString());
        rock_64->setText(QString());
        rock_65->setText(QString());
        rock_66->setText(QString());
        rock_67->setText(QString());
        rock_68->setText(QString());
        box_8->setText(QString());
        box_9->setText(QString());
        rock_69->setText(QString());
        rock_70->setText(QString());
        rock_71->setText(QString());
        rock_72->setText(QString());
        rock_73->setText(QString());
        rock_74->setText(QString());
        rock_75->setText(QString());
        rock_76->setText(QString());
        rock_77->setText(QString());
        rock_78->setText(QString());
        rock_79->setText(QString());
        rock_80->setText(QString());
        bottom_1->setText(QString());
        bottom_2->setText(QString());
        bottom_3->setText(QString());
        egg->setText(QApplication::translate("MainWindow", "TextLabel", 0));
        break_1->setText(QApplication::translate("MainWindow", "TextLabel", 0));
        break_2->setText(QApplication::translate("MainWindow", "TextLabel", 0));
        break_3->setText(QApplication::translate("MainWindow", "TextLabel", 0));
        num_1->setText(QApplication::translate("MainWindow", "<html><head/><body><p><span style=\" color:#ff0000;\">num1</span></p></body></html>", 0));
        num_2->setText(QApplication::translate("MainWindow", "<html><head/><body><p><span style=\" color:#ff5500;\">num2</span></p></body></html>", 0));
        num_3->setText(QApplication::translate("MainWindow", "<html><head/><body><p><span style=\" color:#ff5500;\">num3</span></p></body></html>", 0));
        num_4->setText(QApplication::translate("MainWindow", "<html><head/><body><p><span style=\" color:#aa00ff;\">num4</span></p></body></html>", 0));
        num_5->setText(QApplication::translate("MainWindow", "<html><head/><body><p><span style=\" color:#aaff00;\">num5</span></p><p><br/></p></body></html>", 0));
        label_4->setText(QApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt; font-weight:600; font-style:italic; color:#ffff00;\">SCORE\357\274\232</span></p></body></html>", 0));
        quit->setText(QString());
        pause->setText(QString());
        label_5->setText(QString());
        again->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
